services:
  web:
    build:
      context: .
      target: runner
      args:
        - GUARDIAN_API_KEY=${GUARDIAN_API_KEY}
        - NEWS_API_KEY=${NEWS_API_KEY}
        - NYT_API_KEY=${NYT_API_KEY}
        - GUARDIAN_API_URL=${GUARDIAN_API_URL}
        - NEWS_API_URL=${NEWS_API_URL}
        - NYT_API_URL=${NYT_API_URL}
        - NYT_API_SECRET=${NYT_API_SECRET}
        - NEXT_PUBLIC_BASE_API_URL=${NEXT_PUBLIC_BASE_API_URL}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - GUARDIAN_API_KEY=${GUARDIAN_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - NYT_API_KEY=${NYT_API_KEY}
      - GUARDIAN_API_URL=${GUARDIAN_API_URL}
      - NEWS_API_URL=${NEWS_API_URL}
      - NYT_API_URL=${NYT_API_URL}
      - NYT_API_SECRET=${NYT_API_SECRET}
      - NEXT_PUBLIC_BASE_API_URL=${NEXT_PUBLIC_BASE_API_URL}
