version: "3.8"
services:
  web:
    build:
      context: .
      target: runner
      args:
        - NEXT_PUBLIC_GUARDIAN_API_KEY=${NEXT_PUBLIC_GUARDIAN_API_KEY}
        - NEXT_PUBLIC_NEWS_API_KEY=${NEXT_PUBLIC_NEWS_API_KEY}
        - NEXT_PUBLIC_NYT_API_KEY=${NEXT_PUBLIC_NYT_API_KEY}
        - NEXT_PUBLIC_GUARDIAN_API_URL=${NEXT_PUBLIC_GUARDIAN_API_URL}
        - NEXT_PUBLIC_NEWS_API_URL=${NEXT_PUBLIC_NEWS_API_URL}
        - NEXT_PUBLIC_NYT_API_URL=${NEXT_PUBLIC_NYT_API_URL}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
